name: PHP Tests

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
      composer:
        required: false
        type: string
      mysql-image:
        required: false
        type: string
      db-name:
        required: false
        type: string
      db-prefix:
        required: false
        type: string

jobs:
  php-tests:
    name: 'PHP Tests ${{ inputs.php-version }}'
    runs-on: ubuntu-latest
    services:
      mysql:
        image: ${{ inputs.mysql-image || 'mysql:8.0' }}
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      DB_PORT: 3306
      DB_DATABASE: ${{ inputs.db-name || 'testbench' }}
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PREFIX: ${{ inputs.db-prefix }}
    steps:
      - name: Checkout changes
        uses: actions/checkout@v4

      - name: Create MySQL Database
        run: |
          sudo systemctl start mysql
          mysql -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }} -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' --port ${{ job.services.mysql.ports['3306'] }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version || '8.3' }}
          extensions: dom, curl, xml, mbstring, zip, pdo, sqlite, bcmath, soap, intl, gd
          tools: composer:v2
          coverage: xdebug

      - name: Set composer version to avoid conflicts
        if: github.head_ref != 'master' && github.head_ref != 'main' && github.head_ref != '4.x'
        run: composer config version 4.0.x-dev

      - name: Install composer dependencies
        run: composer ${{ inputs.composer || 'install --no-interaction --no-progress --no-scripts' }}

      - name: Run test suite
        run: composer test

      - name: Remove composer version after use
        if: github.head_ref != 'master' && github.head_ref != 'main' && github.head_ref != '4.x'
        run: composer config --unset version
